spring:
  config:
    import: aws-parameterstore:/config/ccs/
  thymeleaf:
    cache: false
  datasource:
    url: ${db.url}
    username: ${db.user}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE

  messages:
    basename: messages

cloud:
  aws:
    credentials:
      profile: ccs.service
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    s3:
      bucket-name: temp-ccs-files
      pre-signed:
        expiration: 60
aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: .

logging:
  config: classpath:logback/logback.xml

jwt:
  secret: ${jwt.secret}
  expiration-ms: 3600000