spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:mysql://pre035.chh5jixw7uel.ap-northeast-2.rds.amazonaws.com:3306/pre35db
    username: master
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

logging:
  config: classpath:logback/logback.xml

jwt:
  secret: ${JWT_KEY}
  expiration: 604800000 #일주일, 만료시간