spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: create  # ?????? ?? ??? ???? drop?? ?? ????.
      properties:
        hibernate:
          format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE


logging:
  config: classpath:logback/logback.xml
